name: CI - MediConnect

on:
  push:
    branches: [ main ]        # Run automatically on main
  pull_request:
    branches: [ main ]        # Run on PRs to main
  workflow_dispatch:           # Allows manual trigger

jobs:
  frontend-ci:
    name: Frontend - Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache frontend dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test

      - name: Build frontend
        run: |
          cd frontend
          npm run build
